function Helper_Plot_Electrode_Area(x_location, Y_lim)
% This is a helper function, it has no purpose when used alone, 
% and can be used in all plot_XXX functions. 
% It is used to plot the estimated area in which the final electrode will be placed,
% and the estimated locations of the electrode contacts.
% the assumption is 

% 
cmap = summer(5);

% Electrode Area - the electrode is 7.5mm long

x_start = min(abs(x_location));
x_end = max(x_start+7.5, min(x_location));

patch([x_start x_start x_end x_end],...
      [Y_lim(1) Y_lim(2) Y_lim(2) Y_lim(1)],...
      cmap(1,:),...
      'FaceAlpha', 0.15,...
      'DisplayName', 'Estimated Electrode Position');

% Contacts
% contacts are 1.5mm wide. distance between each is 0.5mm.

% C1
C1_start = x_start;
C1_end = C1_start + 1.5;
patch([C1_start C1_start C1_end C1_end],...
      [Y_lim(1) Y_lim(2) Y_lim(2) Y_lim(1)],...
      cmap(2,:),...
      'FaceAlpha', 0.2,...
      'DisplayName', 'Contact 1');

% C2
C2_start = C1_end + 0.5;
C2_end = C2_start + 1.5;
patch([C2_start C2_start C2_end C2_end],...
      [Y_lim(1) Y_lim(2) Y_lim(2) Y_lim(1)],...
      cmap(3,:),...
      'FaceAlpha', 0.2,...
      'DisplayName', 'Contact 2');


% C3
C3_start = C2_end + 0.5;
C3_end = C3_start + 1.5;
patch([C3_start C3_start C3_end C3_end],...
      [Y_lim(1) Y_lim(2) Y_lim(2) Y_lim(1)],...
      cmap(4,:),...
      'FaceAlpha', 0.2,...
      'DisplayName', 'Contact 3');

% C4
C4_start = C3_end + 0.5;
C4_end = C4_start + 1.5;
patch([C4_start C4_start C4_end C4_end],...
      [Y_lim(1) Y_lim(2) Y_lim(2) Y_lim(1)],...
      cmap(5,:),...
      'FaceAlpha', 0.2,...
      'DisplayName', 'Contact 4');

end

